#!/bin/sh

MONITOR_NAME="Virtual-1"
xrandr -s 1920x1080
pgrep -x sxhkd > /dev/null || sxhkd &
picom -f &
feh --no-fehbg --bg-scale ~/Downloads/gentoo-wallpaper.png &
polybar mainbar &


bspc monitor $MONITOR_NAME -d 1 2 3 4 5

bspc config border_width 	1
bspc config window_gap		8
bspc config split_ratio		0.5
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr &
